import './globals.css';

import { Dosis } from 'next/font/google';

const dosis = Dosis({
  subsets: ['latin'],
  weight: ['200', '400', '600', '700'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-slate-300">
      <body className={dosis.className}>{children}</body>
    </html>
  );
}
